name: Docker Integration

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/summarization_image:latest

      - name: Deploy to Render
        run: |
          docker login -u "_token" -p "${{ secrets.RENDER_TOKEN }}" render-deploy.onrender.com
          docker tag ${{ secrets.DOCKER_USERNAME }}/summarization_image:latest render-deploy.onrender.com/text-summarization:latest
          docker push render-deploy.onrender.com/text-summarization:latest